version: "3.7"
services:
  app:
    image: "esamarathon/esacontroller"
    build: .
    ports:
      - "3333:3333"
  rack1:
    image: "esamarathon/esarack:latest"
    environment: 
      - "ESARACK_MODE=demo"
  rack2:
    image: "esamarathon/esarack:latest"
    environment: 
      - "ESARACK_MODE=demo"
  rack3:
    image: "esamarathon/esarack:latest"
    environment: 
      - "ESARACK_MODE=demo"
    